### ISSUE TITLE
请问用您这个脚本编译r2s除了修改.config还需要修改别的地方吗

### ISSUE THREAD

**Issue by rianjskis** [potoo0/Actions-OpenWrt-0515#1]

**Comment by potoo0** [comment]
不需要。
配置中一般来说编译时除自己选择的插件和主题外，只需要修改与机器 cpu 架构的相关配置，也就是配置菜单中的前三个：
- Target System
- Subtarget
- Target Profile

以及输出的镜像格式:
- Target Images  SquashFS 还是 EXT4 

对于 n5105（x86 64位的 cpu）我的这几个配置是(这也是 lede 的默认值):
```bash
- Target System: (x86)
- Subtarget: (x86_64)
- Target Profile: (Generic x86/64)
- Target Images: SquashFS 
```

**Comment by rianjskis** [comment]
> 不需要。 配置中一般来说编译时除自己选择的插件和主题外，只需要修改与机器 cpu 架构的相关配置，也就是配置菜单中的前三个：
> 
>     * 目标系统
> 
>     * 子目标
> 
>     * 目标配置文件
> 
> 
> 以及输出的镜像格式:
> 
>     * Target Images  SquashFS 还是 EXT4
> 
> 
> 对于 n5105（x86 64位的 cpu）我的这几个配置是(这也是 lede 的默认值):
> 
> ```shell
> - Target System: (x86)
> - Subtarget: (x86_64)
> - Target Profile: (Generic x86/64)
> - Target Images: SquashFS 
> ```

感谢老哥提点.我是把在虚拟机中选择好的.config文件上传到仓库的,但是老是出错,老哥有时间能帮我看看原因吗.
https://github.com/rianjskis/OpenWrt-R2s
这是我仓库的地址
